### ISSUE TITLE
关于`minapp-wx/typing/wx.d.ts`的一点疑问

### ISSUE THREAD

**Issue by suguanYang** [wx-minapp/minapp-wx#1]
`request`作为命名空间`wx`下的一个方法，为何又要用一个命名空间？

**Comment by qiu8310** [comment]
namespace 可以管理定义的类型， typescript 里面类型很重要，有时候我们可能不仅仅只会调用 wx.request 方法，有时候可能就是需要 request 方法的参数类型。这个时候就可以这样用：

```ts
let requestParam: wx.request.Param
```

另外，所有函数中的参数的类型命名是有一定规律的（很容易发现）

**Comment by suguanYang** [comment]
> namespace 可以管理定义的类型， typescript 里面类型很重要，有时候我们可能不仅仅只会调用 wx.request 方法，有时候可能就是需要 request 方法的参数类型。这个时候就可以这样用：
> 
> ```ts
> let requestParam: wx.request.Param
> ```
> 
> 另外，所有函数中的参数的类型命名是有一定规律的（很容易发现）

多谢解答。我大概理解了使用嵌套命名空间的意义，但是这样在使用`wx.request`的时候*代码提示*会是一个命名空间，这样也许会造成误解, 可以单独的使用一个`Request`来作为命名空间

**Comment by qiu8310** [comment]
刚开始我是按你说的方法做的（当时还在每个类型前加了一个字母 `I`），这样做有个不好的地方是当输入 `wx.` 时，会出现一大堆自动补全，不方便定位和查找。而按现在的这种方案，输入 `wx.` 只会出现微信支持的方法，非常直观、明了。

刚开始其实我也不喜欢现在这种写法，但习惯了之后我越来越喜欢，我现在甚至在我的其它项目中都是这样做的，因为如果要用某个函数，我不需要思考就知道这个函数的参数和返回值的 ts 类型（比如 request 函数，它的参数是 request.Param，它的返回值是 request.Rtn，即使不知道，输入 request 也会自动提示支持的类型）

**Comment by qiu8310** [comment]
另外还有个好处是，只需要导出一个 request，而你的方案需要导出一个 request 和 Request。导出一个字段在 ts 中使用起来也方便。

**Comment by suguanYang** [comment]
额，这样啊，的确好处多多。多谢赐教
